name = "coming-soon"

send_email = [
    { type = "send_email", name = "NO_REPLY_EMAIL", destination_address = "no-reply@timsexperiments.foo" },
]

kv_namespaces = [
    { binding = "NEWS_LETTER_KV", id = "acc7679be0c345cebd7a1345d52abcf8", preview_id = "d366f54af4bb45838291d9055e564bc7" },
]
